AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation for Padel-Booking: ECR and ECS with Fargate'

Resources:
  PadelBookingRepository:
    Type: 'AWS::ECR::Repository'
    Properties:
      RepositoryName: padel-booking-repo

  PadelBookingCluster:
    Type: 'AWS::ECS::Cluster'
    Properties:
      ClusterName: padel-booking-cluster

  PadelBookingExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: AmazonECSTaskExecutionRolePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'ecr:GetAuthorizationToken'
                  - 'ecr:BatchCheckLayerAvailability'
                  - 'ecr:GetDownloadUrlForLayer'
                  - 'ecr:GetRepositoryPolicy'
                  - 'ecr:DescribeRepositories'
                  - 'ecr:ListImages'
                  - 'ecr:DescribeImages'
                  - 'ecr:BatchGetImage'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: '*'

  PadelBookingTaskDefinition:
    Type: 'AWS::ECS::TaskDefinition'
    Properties:
      Family: padel-booking-task
      Cpu: '256'
      Memory: '512'
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !GetAtt PadelBookingExecutionRole.Arn
      ContainerDefinitions:
        - Name: padel-booking-container
          Image: !Join ['', [!Ref 'AWS::AccountId', '.dkr.ecr.', !Ref 'AWS::Region', '.amazonaws.com/padel-booking-repo:latest']]
          Memory: 512
          Cpu: 256
          Essential: true
          PortMappings:
            - ContainerPort: 3000
